export const UserName = 'admin'
export const Password = 'admin'
export const Wrong_Details = 'Username or Password incorrect'
export const Blank_UserName = 'Username can not be blank'
export const Blank_Password = 'Password can not be blank'
